In [183]:
import pandas as pd
import numpy as np

In [184]:
dados_brutos = pd.read_csv('pokemon_sujo_para_etl.csv')
df = dados_brutos.copy()

In [185]:
df["name"] = df["name"].str.strip()
df["name"] = df["name"].str.lower()
df["name"] = df["name"].str.capitalize()
print(df["name"].head(10))

0           Bulbasaur
1             Ivysaur
2            Venusaur
3       Venusaur-mega
4       Venusaur-gmax
5          Charmander
6          Charmeleon
7           Charizard
8    Charizard-mega-x
9    Charizard-mega-y
Name: name, dtype: str

In [186]:
df["type1"] = df["type1"].str.strip()
df["type1"] = df["type1"].str.lower()
df["type1"] = df["type1"].str.capitalize()
df["type2"] = df["type2"].str.strip()
df["type2"] = df["type2"].str.lower()
df["type2"] = df["type2"].str.capitalize()
df["type2"] = df["type2"].replace("No_type", "None")
print(df["type2"].head(10))
print(df["type1"].head(10))

0    Poison
1    Poison
2    Poison
3    Poison
4    Poison
5      None
6      None
7    Flying
8    Dragon
9    Flying
Name: type2, dtype: str
0    Grass
1    Grass
2    Grass
3    Grass
4    Grass
5     Fire
6     Fire
7     Fire
8     Fire
9     Fire
Name: type1, dtype: str

In [187]:
df["ability1"] = df["ability1"].str.strip()
df["ability1"] = df["ability1"].str.lower()
df["ability1"] = df["ability1"].str.capitalize()
df["ability2"] = df["ability2"].str.strip()
df["ability2"] = df["ability2"].str.lower()
df["ability2"] = df["ability2"].str.capitalize()

df["ability2"] = df["ability2"].replace("N/a", "None")
df["ability2"] = df["ability2"].replace("No_ability", "None") 
df["ability2"] = df["ability2"].replace("Nan", "None")
df["ability2"] = df["ability2"].replace("Null", "None")
df["ability2"] = df["ability2"].replace("Sem_habilidade", "None")
df["ability2"] = df["ability2"].replace("No-ability", "None")
df["ability2"] = df["ability2"].replace("", "None")
df["ability2"] = df["ability2"].fillna("None")


print(df["ability2"].head(100))
lista = [df["ability2"].iloc[i] for i in range(300)]
print(lista)

0            None
1            None
2            None
3            None
4            None
         ...
95    Anger-point
96    Anger-point
97     Flash-fire
98     Flash-fire
99     Flash-fire
Name: ability2, Length: 100, dtype: str
['None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'Tangled-feet', 'Tangled-feet', 'Tangled-feet', 'None', 'Guts', 'Hustle', 'Guts', 'Hustle', 'Hustle', 'None', 'None', 'Shed-skin', 'Shed-skin', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'Rivalry', 'Rivalry', 'Rivalry', 'Rivalry', 'Rivalry', 'Rivalry', 'Magic-guard', 'Magic-guard', 'None', 'None', 'None', 'None', 'Competitive', 'Competitive', 'None', 'None', 'None', 'None', 'None', 'Dry-skin', 'Dry-skin', 'Tinted-lens', 'Tinted-lens', 'Arena-trap', 'Tangling-hair', 'Arena-trap', 'Tangling-hair', 'Technician', 'Technician', 'Tough-claws', 'Technician', 'Technician', 'Technician', 'Cloud-nine', 'Cloud-nine', 'Anger-point', 'Anger-point', 'Flash-fire', 'Flash-fire', 'Flash-fire', 'Flash-fire', 'Damp', 'Damp', 'Damp', 'Inner-focus', 'Inner-focus', 'Inner-focus', 'None', 'No-guard', 'No-guard', 'No-guard', 'No-guard', 'None', 'None', 'None', 'Liquid-ooze', 'Liquid-ooze', 'Sturdy', 'Sturdy', 'Sturdy', 'Sturdy', 'Sturdy', 'Sturdy', 'Flash-fire', 'Pastel-veil', 'Flash-fire', 'Pastel-veil', 'Own-tempo', 'Own-tempo', 'Own-tempo', 'None', 'Own-tempo', 'Sturdy', 'Sturdy', 'Inner-focus', 'None', 'Early-bird', 'Early-bird', 'Hydration', 'Hydration', 'Sticky-hold', 'Gluttony', 'Sticky-hold', 'Gluttony', 'Skill-link', 'Skill-link', 'None', 'None', 'None', 'None', 'None', 'Sturdy', 'Forewarn', 'Forewarn', 'Shell-armor', 'Shell-armor', 'Shell-armor', 'Static', 'Static', 'Static', 'Static', 'None', 'None', 'None', 'Lightning-rod', 'Lightning-rod', 'Lightning-rod', 'Lightning-rod', 'Reckless', 'Iron-fist', 'Oblivious', 'Neutralizing-gas', 'Neutralizing-gas', 'Neutralizing-gas', 'Rock-head', 'Rock-head', 'Serene-grace', 'Leaf-guard', 'Scrappy', 'None', 'Sniper', 'Sniper', 'Water-veil', 'Water-veil', 'Natural-cure', 'Natural-cure', 'Filter', 'Screen-cleaner', 'Technician', 'Forewarn', 'None', 'None', 'Mold-breaker', 'None', 'Anger-point', 'Anger-point', 'Anger-point', 'Anger-point', 'None', 'None', 'None', 'Shell-armor', 'Shell-armor', 'None', 'Adaptability', 'Adaptability', 'Adaptability', 'None', 'None', 'None', 'Download', 'Shell-armor', 'Shell-armor', 'Battle-armor', 'Battle-armor', 'Pressure', 'None', 'Thick-fat', 'Thick-fat', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'None', 'Keen-eye', 'Keen-eye', 'Keen-eye', 'Keen-eye', 'Early-bird', 'Early-bird', 'Insomnia', 'Insomnia', 'None', 'Illuminate', 'Illuminate', 'None', 'Magic-guard', 'Competitive', 'Serene-grace', 'Serene-grace', 'Early-bird', 'Early-bird', 'None', 'None', 'None', 'None', 'None', 'Huge-power', 'Huge-power', 'Rock-head', 'Damp', 'Leaf-guard', 'Leaf-guard', 'Leaf-guard', 'Pickup', 'Solar-power', 'Solar-power', 'Compound-eyes', 'Water-absorb', 'Water-absorb', 'Water-absorb', 'None', 'None', 'Super-luck', 'Own-tempo', 'Own-tempo', 'None', 'None', 'None', 'Early-bird', 'None', 'None', 'Run-away', 'Sand-veil', 'Sturdy', 'None', 'Run-away', 'Quick-feet', 'Swift-swim', 'Swift-swim', 'Technician', 'None']

In [188]:
df["hidden_ability"] = df["hidden_ability"].str.strip()
df["hidden_ability"] = df["hidden_ability"].str.lower()
df["hidden_ability"] = df["hidden_ability"].str.capitalize()

print(df["hidden_ability"].head(100))

0     Chlorophyll
1     Chlorophyll
2     Chlorophyll
3            None
4     Chlorophyll
         ...
95        Defiant
96        Defiant
97      Justified
98      Rock-head
99      Justified
Name: hidden_ability, Length: 100, dtype: str

In [189]:
df["total_stats"] = df["hp"] + df["attack"] + df["defense"] + df["sp_atk"] + df["sp_def"] + df["speed"]

In [190]:
romanos = {'i': '1', 'ii': '2', 'iii': '3', 'iv': '4', 'v': '5', 'vi': '6', 'vii': '7', 'viii': '8', 'ix': '9'}

df["generation"] = df["generation"].astype(str)
df["generation"] = df["generation"].str.strip()
df["generation"] = df["generation"].str.lower()
df["generation"] = df["generation"].replace(" ", "")
df['generation'] = df['generation'].str.split('-').str[-1].map(romanos)

lista = []
for i in range(1, len(df)):
    if pd.isna(df["generation"].iloc[i]):
        # para o Pandas aceitar a alteração real no loop idêntico, usa-se o .iat
        df.iat[i, df.columns.get_loc("generation")] = df["generation"].iloc[i - 1]
    
    lista.append(df["generation"].iloc[i])

# print(len(lista))
# print(lista)
# lista feita para verificar se o loop acima funcionou corretamente

In [191]:
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].astype(str)
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.strip()
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.lower()
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.replace("no_usage", "0.0")
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.replace("nousage", "0.0")
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.replace("none", "0.0")
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.replace("no usage", "0.0")
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.replace("no", "0.0")
df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].str.replace("zero", "0.0")

df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].replace(["", "-"], np.nan)

df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].fillna("0.0")

df["Smogon_VGC_Usage_2022"] = np.where(
    df["Smogon_VGC_Usage_2022"].str.contains("-", na=False, regex=False), 
    "0.0", 
    df["Smogon_VGC_Usage_2022"]
)

df["Smogon_VGC_Usage_2022"] = df["Smogon_VGC_Usage_2022"].astype(float)

# lista = []
# for i in range(1, len(df)):
#     if df["Smogon_VGC_Usage_2022"].iloc[i] not in lista:
#         lista.append(df["Smogon_VGC_Usage_2022"].iloc[i])

# print(lista)

In [192]:
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].astype(str)
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.strip()
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.lower()
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.replace("nousage", "0.0")
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.replace("none", "0.0")
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.replace("no usage", "0.0")
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.replace("no", "0.0")
df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].str.replace("zero", "0.0")

df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].replace(["", "-"], np.nan)

df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].fillna("0.0")

df["Smogon_VGC_Usage_2023"] = np.where(
    df["Smogon_VGC_Usage_2023"].str.contains("-", na=False, regex=False), 
    "0.0", 
    df["Smogon_VGC_Usage_2023"]
)

df["Smogon_VGC_Usage_2023"] = df["Smogon_VGC_Usage_2023"].astype(float)

# lista1 = []
# for i in range(1, len(df)):
#     if df["Smogon_VGC_Usage_2023"].iloc[i] not in lista1:
#         lista1.append(df["Smogon_VGC_Usage_2023"].iloc[i])

# print(lista1)

In [193]:
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].astype(str)
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.strip()
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.lower()
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.replace("nousage", "0.0")
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.replace("none", "0.0")
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.replace("no usage", "0.0")
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.replace("no", "0.0")
df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].str.replace("zero", "0.0")

df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].replace(["", "-"], np.nan)

df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].fillna("0.0")

df["Smogon_VGC_Usage_2024"] = np.where(
    df["Smogon_VGC_Usage_2024"].str.contains("-", na=False, regex=False), 
    "0.0", 
    df["Smogon_VGC_Usage_2024"]
)

df["Smogon_VGC_Usage_2024"] = df["Smogon_VGC_Usage_2024"].astype(float)

# lista1 = []
# for i in range(1, len(df)):
#     if df["Smogon_VGC_Usage_2024"].iloc[i] not in lista1:
#         lista1.append(df["Smogon_VGC_Usage_2024"].iloc[i])
# print(lista1)

In [194]:
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].astype(str)
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.strip()
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.lower()
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.replace("nousage", "0.0")
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.replace("none", "0.0")
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.replace("no usage", "0.0")
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.replace("no", "0.0")
df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].str.replace("zero", "0.0")

df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].replace(["", "-"], np.nan)

df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].fillna("0.0")

df["Worlds_VGC_Usage_2022"] = df["Worlds_VGC_Usage_2022"].astype(float)

# lista1 = []
# for i in range(1, len(df)):
#     if df["Worlds_VGC_Usage_2022"].iloc[i] not in lista1:
#         lista1.append(df["Worlds_VGC_Usage_2022"].iloc[i])
# print(lista1)

In [195]:
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].astype(str)
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.strip()
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.lower()
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.replace("nousage", "0.0")
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.replace("none", "0.0")
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.replace("no usage", "0.0")
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.replace("no", "0.0")
df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].str.replace("zero", "0.0")

df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].replace(["", "-"], np.nan)

df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].fillna("0.0")

df["Worlds_VGC_Usage_2023"] = df["Worlds_VGC_Usage_2023"].astype(float)

# lista1 = []
# for i in range(1, len(df)):
#     if df["Worlds_VGC_Usage_2023"].iloc[i] not in lista1:
#         lista1.append(df["Worlds_VGC_Usage_2023"].iloc[i])

# print(lista1)

In [196]:
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].astype(str)
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.strip()
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.lower()
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.replace("nousage", "0.0")
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.replace("none", "0.0")
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.replace("no usage", "0.0")
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.replace("no", "0.0")
df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].str.replace("zero", "0.0")

df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].replace(["", "-"], np.nan)

df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].fillna("0.0")

df["Worlds_VGC_Usage_2024"] = df["Worlds_VGC_Usage_2024"].astype(float)

# lista1 = []
# for i in range(1, len(df)):
#     if df["Worlds_VGC_Usage_2024"].iloc[i] not in lista1:
#         lista1.append(df["Worlds_VGC_Usage_2024"].iloc[i])

# print(lista1)

In [197]:
!pip install fastparquet --quiet

df.to_parquet('pokemon_limpo.parquet', index=False, engine='fastparquet')
print("✓ Dados limpos exportados com sucesso para 'pokemon_limpo.parquet'!")
print("✓ DataFrame mantido em memória pronto para a ingestão no Neo4j.")

✓ Dados limpos exportados com sucesso para 'pokemon_limpo.parquet'!
✓ DataFrame mantido em memória pronto para a ingestão no Neo4j.

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

NEOJ4

In [198]:
!pip install neo4j --quiet
from neo4j import GraphDatabase
import os
from dotenv import load_dotenv


load_dotenv()

URI = os.getenv("NEO4J_URI")
AUTH = (os.getenv("NEO4J_USERNAME"), os.getenv("NEO4J_PASSWORD"))

driver = GraphDatabase.driver(
    URI,
    auth=AUTH
)

with driver.session() as session:
    result = session.run(
        "RETURN 'Conectado com sucesso!' AS status"
    )
    print(result.single()["status"])

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Conectado com sucesso!

In [199]:
query_delete = "MATCH (n) DETACH DELETE n"

with driver.session() as session:
    session.run(query_delete)
    print("BANCO APAGADO")

BANCO APAGADO

In [200]:
print("Iniciando a carga de dados otimizada em lote no Neo4j...")

lista_pokemons = []
for _, linha in df.iterrows():
    lista_pokemons.append({
        'name': str(linha['name']),
        'index': int(linha['index']),
        'hp': int(linha['hp']),
        'attack': int(linha['attack']),
        'defense': int(linha['defense']),
        'sp_atk': int(linha['sp_atk']),
        'sp_def': int(linha['sp_def']),
        'speed': int(linha['speed']),
        'generation': str(linha['generation']),
        'type1': str(linha['type1']),
        'type2': str(linha['type2']),
        'ability1': str(linha['ability1']),
        'ability2': str(linha['ability2']),
        'hidden_ability': str(linha['hidden_ability']),
        'smogon_2022': float(linha['Smogon_VGC_Usage_2022']),
        'smogon_2023': float(linha['Smogon_VGC_Usage_2023']),
        'smogon_2024': float(linha['Smogon_VGC_Usage_2024']),
        'worlds_2022': float(linha['Worlds_VGC_Usage_2022']),
        'worlds_2023': float(linha['Worlds_VGC_Usage_2023']),
        'worlds_2024': float(linha['Worlds_VGC_Usage_2024'])
    })

query_lote = """
UNWIND $linhas AS linha

MERGE (p:Pokemon {name: linha.name})
SET p.pokedex_number = linha.index,
    p.hp = linha.hp,
    p.attack = linha.attack,
    p.defense = linha.defense,
    p.sp_atk = linha.sp_atk,
    p.sp_def = linha.sp_def,
    p.speed = linha.speed,
    p.generation = linha.generation

MERGE (t1:Tipo {nome: linha.type1})    
MERGE (p)-[:POSSUI_TIPO {ordem: "principal"}]->(t1)

FOREACH (_ IN CASE WHEN linha.type2 <> 'None' THEN [1] ELSE [] END |
    MERGE (t2:Tipo {nome: linha.type2})
    MERGE (p)-[:POSSUI_TIPO {ordem: "secundario"}]->(t2)
)

MERGE (a1:Habilidade {nome: linha.ability1})
MERGE (p)-[:POSSUI_HABILIDADE {tipo: "comum"}]->(a1)

FOREACH (_ IN CASE WHEN linha.ability2 <> 'None' THEN [1] ELSE [] END |
    MERGE (a2:Habilidade {nome: linha.ability2})
    MERGE (p)-[:POSSUI_HABILIDADE {tipo: "comum"}]->(a2)
)

FOREACH (_ IN CASE WHEN linha.hidden_ability <> 'None' THEN [1] ELSE [] END |
    MERGE (ha:Habilidade {nome: linha.hidden_ability})
    MERGE (p)-[:POSSUI_HABILIDADE {tipo: "oculta"}]->(ha)
)

MERGE (st22:Torneio {nome: "Smogon VGC", ano: 2022})
MERGE (p)-[r1:COMPETIU_EM]->(st22) SET r1.taxa_uso = linha.smogon_2022

MERGE (st23:Torneio {nome: "Smogon VGC", ano: 2023})
MERGE (p)-[r2:COMPETIU_EM]->(st23) SET r2.taxa_uso = linha.smogon_2023

MERGE (st24:Torneio {nome: "Smogon VGC", ano: 2024})
MERGE (p)-[r3:COMPETIU_EM]->(st24) SET r3.taxa_uso = linha.smogon_2024   

MERGE (wt22:Torneio {nome: "Worlds VGC", ano: 2022})
MERGE (p)-[r4:COMPETIU_EM]->(wt22) SET r4.taxa_uso = linha.worlds_2022

MERGE (wt23:Torneio {nome: "Worlds VGC", ano: 2023})
MERGE (p)-[r5:COMPETIU_EM]->(wt23) SET r5.taxa_uso = linha.worlds_2023   

MERGE (wt24:Torneio {nome: "Worlds VGC", ano: 2024})
MERGE (p)-[r6:COMPETIU_EM]->(wt24) SET r6.taxa_uso = linha.worlds_2024
"""

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        session.run(query_lote, linhas=lista_pokemons)

print("✓ Sucesso! Todos os dados injetados de uma só vez em lote.")

Iniciando a carga de dados otimizada em lote no Neo4j...
✓ Sucesso! Todos os dados injetados de uma só vez em lote.

In [201]:
query = """
MATCH (p:Pokemon)-[r:COMPETIU_EM]->(t:Torneio)
RETURN p.name AS Pokemon, r.taxa_uso AS TaxaUso, t.nome AS Torneio, t.ano AS Ano
LIMIT 10
"""

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        resultado = session.run(query)
        df1 = pd.DataFrame(resultado.data())

print(df1)
print(50*'=')

            Pokemon  TaxaUso     Torneio   Ano
0     Venusaur-mega  0.00000  Smogon VGC  2022
1     Venusaur-gmax  0.00000  Smogon VGC  2022
2        Charmander  0.00000  Smogon VGC  2022
3        Charmeleon  0.00000  Smogon VGC  2022
4         Charizard  7.17374  Smogon VGC  2022
5  Charizard-mega-x  0.00000  Smogon VGC  2022
6  Charizard-mega-y  0.00000  Smogon VGC  2022
7    Charizard-gmax  0.00000  Smogon VGC  2022
8          Squirtle  0.00000  Smogon VGC  2022
9         Wartortle  0.00000  Smogon VGC  2022
==================================================


## Categoria 1 — Consultas Básicas (Mapeamento de Estrutura Básica)

Top 10 Pokémon com Maior Velocidade Base

In [202]:
query_1 = """
MATCH (p:Pokemon)
RETURN p.name AS Pokemon, p.speed AS Velocidade, p.generation AS Geracao
ORDER BY Velocidade DESC LIMIT 10
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_1).data()))

           Pokemon  Velocidade Geracao
0        Regieleki         200       8
1     Deoxys-speed         180       3
2          Ninjask         160       3
3        Pheromosa         151       7
4  Aerodactyl-mega         150       1
5  Electrode-hisui         150       1
6    Deoxys-normal         150       3
7    Alakazam-mega         150       1
8        Electrode         150       1
9    Deoxys-attack         150       3

Distribuição de Pokémon por Tipo Primário

In [203]:
query_2 = """
MATCH (p:Pokemon)-[:POSSUI_TIPO {ordem: "principal"}]->(t:Tipo)
RETURN t.nome AS Tipo, COUNT(p) AS QtdPokemon
ORDER BY QtdPokemon DESC
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_2).data()))

        Tipo  QtdPokemon
0      Water         158
1     Normal         138
2      Grass         118
3   Electric          96
4        Bug          93
5    Psychic          83
6       Rock          81
7       Fire          80
8       Dark          59
9   Fighting          57
10    Dragon          52
11    Poison          51
12     Ghost          51
13     Steel          49
14    Ground          48
15       Ice          43
16     Fairy          33
17    Flying          13

As 10 Habilidades mais Comuns no Universo Pokémon

In [204]:
query_3 = """
MATCH (p:Pokemon)-[:POSSUI_HABILIDADE]->(h:Habilidade)
RETURN h.nome AS Habilidade, COUNT(p) AS QtdPokemon
ORDER BY QtdPokemon DESC LIMIT 10
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_3).data()))

    Habilidade  QtdPokemon
0       Sturdy          48
1   Swift-swim          48
2   Intimidate          46
3     Keen-eye          43
4     Levitate          42
5  Chlorophyll          39
6     Gluttony          39
7  Inner-focus          38
8       Static          38
9        Frisk          38

## Categoria 2 — CONSULTAS COMPLEXAS (Interconexão Multidimensional de Caminhos)

O Caminho da Dominância Oculta

In [205]:
query_4 = """
MATCH (h:Habilidade)<-[:POSSUI_HABILIDADE {tipo: "oculta"}]-(p:Pokemon)-[r:COMPETIU_EM]->(t:Torneio {ano: 2024})
WHERE r.taxa_uso > 15.0
RETURN p.name AS Pokemon, 
       h.nome AS HabilidadeOculta, 
       r.taxa_uso AS TaxaUso, 
       t.nome AS Torneio
ORDER BY TaxaUso DESC
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_4).data()))

               Pokemon HabilidadeOculta   TaxaUso     Torneio
0             Sneasler     Poison-touch  38.21000  Worlds VGC
1           Incineroar       Intimidate  36.81468  Smogon VGC
2           Incineroar       Intimidate  32.40000  Worlds VGC
3            Rillaboom     Grassy-surge  29.72000  Worlds VGC
4            Kingambit         Pressure  26.78000  Worlds VGC
5            Amoonguss      Regenerator  26.58000  Worlds VGC
6   Tornadus-incarnate          Defiant  26.15361  Smogon VGC
7           Archaludon         Stalwart  22.70000  Worlds VGC
8            Rillaboom     Grassy-surge  22.31496  Smogon VGC
9            Dragonite       Multiscale  21.84000  Worlds VGC
10           Amoonguss      Regenerator  19.88122  Smogon VGC
11            Pelipper        Rain-dish  19.51000  Worlds VGC
12           Primarina     Liquid-voice  17.33000  Worlds VGC
13  Landorus-incarnate      Sheer-force  17.08534  Smogon VGC
14          Annihilape          Defiant  16.80000  Worlds VGC
15           Farigiraf       Sap-sipper  16.52409  Smogon VGC
16            Garchomp       Rough-skin  16.46000  Worlds VGC

Interseção de Tipos Opostos via Sinergia de Habilidade Compartilhada

In [206]:
query_5 = """
MATCH (t1:Tipo {nome: "Fire"})<-[:POSSUI_TIPO]-(p1:Pokemon)-[:POSSUI_HABILIDADE]->(h:Habilidade)
MATCH (t2:Tipo {nome: "Water"})<-[:POSSUI_TIPO]-(p2:Pokemon)-[:POSSUI_HABILIDADE]->(h)
RETURN h.nome AS HabilidadeCompartilhada, 
       p1.name AS PokemonFogo, 
       p2.name AS PokemonAgua
ORDER BY HabilidadeCompartilhada ASC
LIMIT 10
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_5).data()))

  HabilidadeCompartilhada          PokemonFogo         PokemonAgua
0             Anger-point  Tauros-paldea-blaze  Tauros-paldea-aqua
1             Anger-point             Camerupt  Tauros-paldea-aqua
2                Cud-chew  Tauros-paldea-blaze  Tauros-paldea-aqua
3             Cursed-body        Marowak-alola            Frillish
4             Cursed-body        Marowak-totem            Frillish
5             Cursed-body        Marowak-alola           Jellicent
6             Cursed-body        Marowak-totem           Jellicent
7                Forecast       Castform-sunny      Castform-rainy
8                Gluttony              Pansear             Panpour
9                Gluttony             Simisear             Panpour

A Teia Completa do Metagame

In [207]:
query_6 = """
MATCH (t:Tipo)<-[:POSSUI_TIPO {ordem: "principal"}]-(p:Pokemon)-[:POSSUI_HABILIDADE {tipo: "comum"}]->(h:Habilidade)
MATCH (p)-[r:COMPETIU_EM]->(torneio:Torneio {ano: 2024})
WHERE r.taxa_uso > 25.0
RETURN torneio.nome AS Torneio, 
       p.name AS Pokemon, 
       t.nome AS TipoPrincipal, 
       h.nome AS HabilidadeDominante, 
       r.taxa_uso AS TaxaUso
ORDER BY TaxaUso DESC
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_6).data()))

       Torneio             Pokemon TipoPrincipal HabilidadeDominante   TaxaUso
0   Smogon VGC        Flutter-mane         Ghost      Protosynthesis  59.43710
1   Worlds VGC            Sneasler      Fighting            Pressure  38.21000
2   Worlds VGC            Sneasler      Fighting            Unburden  38.21000
3   Smogon VGC          Incineroar          Fire               Blaze  36.81468
4   Smogon VGC  Ogerpon-wellspring         Grass        Water-absorb  35.07103
5   Worlds VGC          Incineroar          Fire               Blaze  32.40000
6   Worlds VGC           Gholdengo         Steel        Good-as-gold  31.41000
7   Worlds VGC           Rillaboom         Grass            Overgrow  29.72000
8   Worlds VGC           Kingambit          Dark             Defiant  26.78000
9   Worlds VGC           Kingambit          Dark    Supreme-overlord  26.78000
10  Worlds VGC           Amoonguss         Grass        Effect-spore  26.58000
11  Smogon VGC  Tornadus-incarnate        Flying           Prankster  26.15361
12  Smogon VGC         Raging-bolt      Electric      Protosynthesis  26.14914
13  Smogon VGC       Urshifu-rapid      Fighting         Unseen-fist  25.61987

## Categoria 3 — Consultas Sérias   (Análise Estratégica do Metagame e Data Analytics)

Centralização do Meta - Concentração de Pokémon no Top Tier (>30% uso) no Worlds

In [208]:
query_7 = """
MATCH (p:Pokemon)-[r:COMPETIU_EM]->(t:Torneio {nome: "Worlds VGC"})
WHERE r.taxa_uso > 30.0
RETURN t.ano AS Ano, 
       p.name AS Pokemon, 
       r.taxa_uso AS TaxaUso, 
       p.generation AS Geracao
ORDER BY Ano ASC, TaxaUso DESC
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_7).data()))

     Ano             Pokemon  TaxaUso Geracao
0   2022          Incineroar    73.41       7
1   2022      Zacian-crowned    53.65       8
2   2022              Kyogre    36.87       3
3   2022          Grimmsnarl    30.40       8
4   2023          Iron-hands    51.32       9
5   2023        Flutter-mane    51.19       9
6   2023    Landorus-therian    45.80       5
7   2023  Ogerpon-wellspring    31.03       9
8   2023             Heatran    30.06       4
9   2024            Sneasler    38.21       8
10  2024          Incineroar    32.40       7
11  2024           Gholdengo    31.41       9

Mapeamento de Hiperconsistência Histórica (Presença nos 6 Torneios Simultâneos)

In [209]:
query_8 = """
MATCH (p:Pokemon)-[r:COMPETIU_EM]->(t:Torneio)
WITH p, 
     COUNT(CASE WHEN r.taxa_uso > 0 THEN 1 END) AS TorneiosAtivos, 
     SUM(r.taxa_uso) AS UsoTotal
WHERE TorneiosAtivos = 6
RETURN p.name AS Pokemon, 
       TorneiosAtivos, 
       ROUND(UsoTotal, 2) AS UsoAcumulado, 
       ROUND(UsoTotal / 6, 2) AS MediaPorTorneio
ORDER BY UsoAcumulado DESC
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_8).data()))

            Pokemon  TorneiosAtivos  UsoAcumulado  MediaPorTorneio
0         Rillaboom               6        149.41            24.90
1         Amoonguss               6        127.17            21.20
2        Grimmsnarl               6         74.62            12.44
3   Indeedee-female               6         58.11             9.69
4           Torkoal               6         38.55             6.42
5    Gastrodon-west               6         37.37             6.23
6   Ninetales-alola               6         27.45             4.57
7    Gastrodon-east               6         26.64             4.44
8          Garchomp               6         24.42             4.07
9         Volcarona               6         22.99             3.83
10         Arcanine               6         22.28             3.71
11       Talonflame               6         20.59             3.43
12        Dragapult               6         20.28             3.38
13        Tyranitar               6         14.51             2.42
14       Gothitelle               6          9.66             1.61
15         Dusclops               6          9.57             1.59
16         Clefairy               6          8.45             1.41
17          Milotic               6          8.19             1.36
18        Hatterene               6          7.93             1.32
19        Hydreigon               6          7.24             1.21
20          Weezing               6          5.23             0.87
21          Sableye               6          5.11             0.85
22        Salamence               6          4.37             0.73
23         Gyarados               6          3.72             0.62
24    Weezing-galar               6          3.51             0.58
25         Bronzong               6          3.10             0.52
26        Azumarill               6          2.71             0.45
27          Snorlax               6          2.52             0.42
28        Mamoswine               6          2.43             0.40
29         Tsareena               6          2.08             0.35
30       Chandelure               6          1.35             0.23

Mapeamento de Habilidades Ocultas Compartilhadas no Top Tier de 2024

In [210]:
query_9 = """
MATCH (h:Habilidade)<-[:POSSUI_HABILIDADE {tipo: "oculta"}]-(p:Pokemon)-[r:COMPETIU_EM]->(t:Torneio {ano: 2024})
WHERE r.taxa_uso > 15.0
WITH h.nome AS HabilidadeOculta, 
     p.name AS Pokemon, 
     AVG(r.taxa_uso) AS MediaUso
RETURN HabilidadeOculta, 
       Pokemon, 
       ROUND(MediaUso, 2) AS TaxaUso
ORDER BY HabilidadeOculta ASC, TaxaUso DESC
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_9).data()))

   HabilidadeOculta             Pokemon  TaxaUso
0           Defiant  Tornadus-incarnate    26.15
1           Defiant          Annihilape    16.80
2      Grassy-surge           Rillaboom    26.02
3        Intimidate          Incineroar    34.61
4      Liquid-voice           Primarina    17.33
5        Multiscale           Dragonite    21.84
6      Poison-touch            Sneasler    38.21
7          Pressure           Kingambit    26.78
8         Rain-dish            Pelipper    19.51
9       Regenerator           Amoonguss    23.23
10       Rough-skin            Garchomp    16.46
11       Sap-sipper           Farigiraf    16.52
12      Sheer-force  Landorus-incarnate    17.09
13         Stalwart          Archaludon    22.70

Análise de Evolução - Top 5 Pokémon Veteranos com Maior Crescimento (2022 vs 2024)

In [211]:
query_10 = """
MATCH (p:Pokemon)-[r22:COMPETIU_EM]->(t22:Torneio {ano: 2022})
MATCH (p)-[r24:COMPETIU_EM]->(t24:Torneio {ano: 2024})
WHERE r22.taxa_uso > 0.0 AND r24.taxa_uso > 0.0
WITH p.name AS Pokemon, 
     AVG(r22.taxa_uso) AS Media22, 
     AVG(r24.taxa_uso) AS Media24
WITH Pokemon, 
     Media22, 
     Media24, 
     (Media24 - Media22) AS Crescimento
RETURN Pokemon, 
       ROUND(Media22, 2) AS UsoMedio_2022, 
       ROUND(Media24, 2) AS UsoMedio_2024, 
       ROUND(Crescimento, 2) AS GanhoDeTaxa
ORDER BY GanhoDeTaxa DESC
LIMIT 20
"""
with GraphDatabase.driver(URI, auth=AUTH) as driver:
    with driver.session() as session:
        display(pd.DataFrame(session.run(query_10).data()))

                 Pokemon  UsoMedio_2022  UsoMedio_2024  GanhoDeTaxa
0          Urshifu-rapid           4.57          25.62        21.05
1         Urshifu-single           7.58          24.98        17.40
2     Landorus-incarnate           0.24          17.09        16.84
3              Dragonite           0.25          16.18        15.94
4     Tornadus-incarnate          13.85          26.15        12.31
5                  Entei           0.95          12.62        11.66
6               Pelipper           0.12          11.74        11.62
7              Primarina           0.09           9.94         9.85
8               Garchomp           0.20           8.33         8.13
9      Calyrex-ice-rider          13.33          20.95         7.62
10       Ninetales-alola           0.08           6.44         6.36
11             Dragapult           1.22           7.48         6.26
12             Volcarona           0.80           5.45         4.65
13             Amoonguss          18.88          23.23         4.35
14         Indeedee-male           0.58           4.93         4.35
15             Cresselia           0.06           4.17         4.10
16               Torkoal           2.64           6.53         3.89
17  Calyrex-shadow-rider          16.27          20.12         3.86
18     Zamazenta-crowned           0.61           4.12         3.51
19             Tyranitar           0.16           3.63         3.47